### ISSUE TITLE
Create an attenuated signal mask

### ISSUE THREAD

**Issue by ruxandra-valcu** [OceanStreamIO/echopype#1]
https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_attenuated.py (MIT licence, compatible)

We'll want this designed as a mask so we can then use various options for interpolation

**Comment by mihaiboldeanu** [comment]
To develop the attenuation masks started from:
https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_attenuated.py
There are two methods described in the sub-module:
ryan and ariza.
 - ryan is tested and works
 - ariza was not fully implemented and we will have to search for publication to get full details of functionality.
 
 To get the ryan function working some aux. functions were required:
from transform sub-module:
- lin
- log

For ariza function more dependencies were required from resample.py 


Tested and compared with:
https://github.com/open-ocean-sounding/echopy/blob/master/tests/masking_attenuated.png

Using the test data from this echopy ftp (https://github.com/open-ocean-sounding/echopy/tree/master/data   ftp://ftp.bas.ac.uk/rapidkrill/ )and 
the files mentioned in https://github.com/open-ocean-sounding/echopy/blob/master/tests/masking_attenuated.py
