### ISSUE TITLE
Add impulse noise mask 

### ISSUE THREAD

**Issue by ruxandra-valcu** [OceanStreamIO/echopype#2]
EchoPy version - https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_impulse.py

**Comment by simedroniraluca** [comment]
I have started developing the impulse noise mask based on the methods provided in the [echopy/processing/mask_impulse.py](https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_impulse.py) sub-module.

This sub-module includes three methods: `ryan`, `ryan_iterable` (which is based on the `ryan` method), and `wang`.

The successful execution of the `ryan`, `ryan_iterable`, and `wang` methods depends on several auxiliary functions from two other sub-modules:

1. From the [transform sub-module](https://github.com/open-ocean-sounding/echopy/blob/master/echopy/utils/transform.py): `lon()` and `lin()`
2. From the [resample sub-module](https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/resample.py): `oned()`, `full()`, and `din2ax()`

I tested and compared my implementation against the following image: [masking_impulse.png](https://github.com/open-ocean-sounding/echopy/blob/master/tests/masking_impulse.png)

The test data was acquired from this [Echopy FTP link](ftp://ftp.bas.ac.uk/rapidkrill/), which is also available in the [Echopy GitHub Data Folder](https://github.com/open-ocean-sounding/echopy/tree/master/data).

**TO DO:** More testing is required.

**Comment by simedroniraluca** [comment]
The `scikit-image` package must be installed in the environment. 

```bash
conda install -c conda-forge scikit-image
```
