### ISSUE TITLE
Add transient noise mask

### ISSUE THREAD

**Issue by ruxandra-valcu** [OceanStreamIO/echopype#3]
https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_transient.py - EchoPy version

**Comment by mihaiboldeanu** [comment]
Completed  #3 starting from [echopy](https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_transient.py).
Transient noise mask is based on to functions:
 - ryan
 - fielding
 Extra function required from [transform.py](https://github.com/open-ocean-sounding/echopy/blob/master/echopy/utils/transform.py) (lin, log).
 
 The functionality is added as get_transient_noise_mask(), and we can specify what type masking we want( ryan or fielding).
