### ISSUE TITLE
Add range mask

### ISSUE THREAD

**Issue by ruxandra-valcu** [OceanStreamIO/echopype#4]
https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_range.py

**Comment by simedroniraluca** [comment]
I have started developing the range mask based on the methods provided in the https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_range.py sub-module.
This sub-module includes four methods: 'above', 'below', 'inside', 'outside'.

**TO DO**: Testing is required.
