### ISSUE TITLE
Add seabed and false seabed detection

### ISSUE THREAD

**Issue by ruxandra-valcu** [OceanStreamIO/echopype#5]
EchoPy version https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_seabed.py

**Comment by mihaiboldeanu** [comment]
The [mask seabed function](https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_seabed.py) require the skimage package. Will add it to the requirement.txt.
