### ISSUE TITLE
Implementing Iterative "Ariza" Method for seabed detection

### ISSUE THREAD

**Issue by simedroniraluca** [OceanStreamIO/echopype#98]
The "ariza" method is used for seabed detection. [Original code here](https://github.com/open-ocean-sounding/echopy/blob/master/echopy/processing/mask_seabed.py). The application of the method depends on the dataset. Below is an example with two sets of parameters used to create and apply a mask for seabed detection for two datasets. To make an automated seabed detection, maybe an iterative "ariza" should be an initial solution.

**Dataset 1**
<img width="503" alt="Screenshot 2023-10-30 at 10 35 32" src="https://github.com/OceanStreamIO/echopype/assets/92971445/8548c4da-6f19-4017-ac5c-969f193215c3">

**Dataset 2**
<img width="522" alt="Screenshot 2023-10-30 at 10 41 54" src="https://github.com/OceanStreamIO/echopype/assets/92971445/a00b465b-b99f-4851-b987-e8101fd7a00f">

**Set 1 parameters**
```
initial "ariza" parameters:
    oceanstream_seabed_mask_params = {
        "r0": 10,
        "r1": 1000,
        "roff": 0,
        "thr": -40,
        "ec": 1,
        "ek": (1, 3),
        "dc": 10,
        "dk": (3, 7),
    }
```
<img width="503" alt="Screenshot 2023-10-30 at 10 37 53" src="https://github.com/OceanStreamIO/echopype/assets/92971445/5be9ac66-7e22-4a39-8c46-95da116108f2">
<img width="516" alt="Screenshot 2023-10-30 at 10 44 12" src="https://github.com/OceanStreamIO/echopype/assets/92971445/7082801d-efb5-4314-869a-9c5232cd2d79">

**Set 2 parameters**
new "ariza" parameters:
    oceanstream_seabed_mask_params = {
        "r0": 10,
        "r1": 1000,
        "roff": 0,
        "thr": -35,
        "ec": 15,
        "ek": (1, 3),
        "dc": 150,
        "dk": (1, 3),
    }
<img width="522" alt="Screenshot 2023-10-30 at 10 40 08" src="https://github.com/OceanStreamIO/echopype/assets/92971445/4b7e71d9-e051-4c29-a447-f3222b1439fc">
<img width="522" alt="Screenshot 2023-10-30 at 10 46 40" src="https://github.com/OceanStreamIO/echopype/assets/92971445/fa1efbe2-db5a-4c03-bf15-fbb38c552925">

**Comment by ruxandra-valcu** [comment]
To be done as part of the rewriting of the seabed detectors using xarray

**Comment by ruxandra-valcu** [comment]
Thought of a different approach  - the ariza function now has a maximum spike parameter that, when set as not None, cuts off any spikes above that value back to seabed level.
